---
- name: apt-get update
  apt: update_cache=yes
  ignore_errors: True
  tags:
      - install

- name: Add nginx PPA and update apt cache
  apt_repository:
    repo: ppa:nginx/stable
    update_cache: yes
    state: present
  tags:
      - install

- name: install required system packages
  apt: name={{ item }} state=latest
  with_items:
      - nginx-extras
  tags:
      - install

- name: remove wrong upstart script
  file: dest=/etc/init/nginx.conf
        state=absent

- name: Delete default nginx conf
  file: dest=/etc/nginx/sites-enabled/default
        state=absent
  notify: nginx reload
  when: nginx_no_default

- name: put nginx.conf
  template: src=nginx/cors_options dest=/etc/nginx/cors_options
  notify: reload nginx
