---
# CentOS specific package installations
- include: RedHat.yml
  when: ansible_os_family  == "RedHat"

- debug: var=ansible_os_family

# Debian specific package installations
- include: Debian.yml
  when: ansible_os_family  == "Debian"

- name: start nginx
  service: name=nginx state=started enabled=yes
  ignore_errors: true
