---
- name: setup nginx
  yum: name=nginx state=present

- name: Delete default nginx conf
  file: dest=/etc/nginx/sites-enabled/default
        state=absent
  notify: nginx reload
  when: nginx_no_default

- name: Delete default nginx conf
  file: dest=/etc/nginx/conf.d/default.conf
        state=absent
  notify: nginx reload
  when: nginx_no_default

- name: put nginx.conf
  template: src=nginx/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: reload nginx
